project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
  preview:
    port: 1234
    browser: true

website:
  title: "Changde Cheng"
  site-url: https://changde-cheng.github.io
  search: false
  navbar:
    right:
      - about.qmd
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=rUa7JoIAAAAJ&hl=en
    # - icon: twitter
    #   text: Twitter
    #   href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com/in/changde-cheng-15550215a/
      - icon: github
        href: https://github.com/changde-cheng
    left:
      # - text: "About"
      #   file: about.qmd
      # - text: "Posts"
      #   file: posts.qmd
      - text: "Working Papers"
        file: preprints.qmd
      - text: "Publications"
        file: featured.qmd
      - text: "More Publications"
        file: publications.qmd
      # - text: "Projects"
      #   file: projects.qmd
format:
  html:
    theme: litera
    css: styles.css

description-meta: "Changde's personal website."

