---
# title: "Join Us"
# listing:
#   contents: people
#   sort: "date desc"
#   type: default
#   categories: false
#   sort-ui: false
#   filter-ui: false
page-layout: article
title-block-banner: false
---



## Opportunities for Student Researchers 

We welcome motivated undergraduate and graduate students from diverse backgrounds (including biology, medicine, statistics, and engineering) to join our research team. Our lab focuses on multi-omics integration, cancer immunogenomics, and machine learning applications in precision oncology, providing students with hands-on experience in cutting-edge computational cancer research.

If you are interested in contributing to impactful research and developing your skills in bioinformatics, computational biology, and cancer genomics, please contact Dr. Changde Cheng at [ ccheng@uabmc.edu ] for more information.

## Postdocs & Bioinformaticians

For inquiries of postdoc or bioinformatician positions, please send a CV to [ ccheng@uabmc.edu ]. Please include a list of publications and details of three references.



