---
#title: "People"
# listing:
#   contents: people
#   sort: "date desc"
#   type: default
#   categories: false
#   sort-ui: false
#   filter-ui: false
page-layout: article
title-block-banner: false
toc: true
toc-title: "Heroes"  
toc-depth: 4
---


<!-- He started his academic journey at [Peking University](https://en.wikipedia.org/wiki/Peking_University), one of China’s most prestigious universities.  He continued to pursue his education and training at  [UCLA](https://en.wikipedia.org/wiki/University_of_California,_Los_Angeles), with Dr. Charles Taylor, a pioneering researcher exploring fundamental questions about language evolution and artificial life; and at the [University of Notre Dame](https://en.wikipedia.org/wiki/University_of_Notre_Dame), with Dr. [Nora Besansky](https://en.wikipedia.org/wiki/Nora_J._Besansky), on ecological genomics of adaptation and speciation. -->

<!-- During his postdoctoral fellowship at the [University of Texas at Austin](https://en.wikipedia.org/wiki/University_of_Texas_at_Austin), he worked with Dr. [Mark Kirkpatrick](https://en.wikipedia.org/wiki/Mark_Kirkpatrick), in population genetics and theoretical biology, and Dr. [David Houle](https://www.bio.fsu.edu/faculty.php?faculty-id=houle), in quantitative genetics and the evolution of complex traits. After that, he worked as a senior/lead computational research scientist at [St. Jude Children's Research Hospital](https://en.wikipedia.org/wiki/St._Jude_Children%27s_Research_Hospital), a world-renowned institution at the forefront of pediatric cancer research and treatment, where he contributed to their mission of finding cures and saving children's lives. -->

<!-- Currently, he serves as a faculty member and head of bioinformatics in the Stem Cell Program and the Institute for Cancer Outcomes and Survivorship at the Heersink School of Medicine, [University of Alabama at Birmingham](https://en.wikipedia.org/wiki/University_of_Alabama_at_Birmingham_School_of_Medicine). His work integrates expertise in genetics, bioinformatics, and computational biology to advance understanding and treatment of cancer and other complex diseases. -->

Meet the lab ~ a team of computational biologists, data scientists, and researchers advancing cancer genomics and precision medicine.

## The Research Champions

### Dr.  Venkata Krishna Chaithanya Manam

Dr. Manam earned his Ph.D. in Electrical and Computer Engineering from [Purdue University](https://en.wikipedia.org/wiki/Purdue_University), where he focused on NLP methods to detect and resolve ambiguities in crowdsourcing tasks, improving clarity and the quality of results with minimal effort from requesters (including publications in [*IEEE Robotics and Automation Letters*]{.underline} and conferences.)  He was an AI & NLP Research Scientist at Reveal AI before joining the lab.

He currently works on multi-modal datasets to discover hidden patterns in cancer research.

### Fadeela Sheini, OD

Fadeela Sheini is a Vision Science PhD student at the University of Alabama at Birmingham (UAB), co-mentored with Dr Maria Grant.  She aims to connect mechanistic research with real world clinical impact.  Her work and training span experimental design and quantitative analysis, to understand how retinal tissues respond to metabolic and ischemic stress.

She is working on lipid metabolism and inflammation in diabetic retinopathy and retinopathy of prematurity, to identify therapeutic strategies that preserve vascular stability and protect retinal function.


## Alumni 

```{r}
#| echo: false
#| warning: false
library(knitr)

df <- data.frame(
  Name = c("Zihao Zhang","Yassin Mreyoud","Doug Welsch", "Brunno Macedo"),
  Role = c("Machine learning, 2025 Fall","Single-cell genomics, 2025 Summer","Bioinformatics, 2024-25", "CML genomics, 2024 Fall"),
  School = c("Chinese Academy of Sciences | Nutrition","WashU | Medicine","Rice | Computer Science", "UFPE, Brazil"),
  Lastknown = c("UAB","UAB | Medicine","Oklahoma Medical Research Foundation | Donczew Lab","UAB | Matlawska Lab")
)

kable(df, format = "html",
      col.names = c("Name", "Project", "From", "Next Chapter"),
      table.attr = "class='table table-striped'")
```


### Yassin Mreyoud - MD/PhD candidate

He was a bioinformatics Scientist at [Washington University School of Medicine in St. Louis](https://en.wikipedia.org/wiki/Washington_University_School_of_Medicine), with multiple publications including one in [*BMC bioinformatics*]{.underline}. Now a MSTP MD/PhD student at UAB.  He is interested in immuno-dysregulation and cellular communication breakdowns that lead to disease.  His work covers multi-omics integration platforms, cell-cell communication algorithms, single-cell analysis pipelines.

<!-- --- -->

### Doug Welsch - Bioinformatician

He earned a Bachelor of Science degree in Computer Science from [William Marsh Rice University](https://en.wikipedia.org/wiki/Rice_University), a leading research university in the United States. During his college years, he also pursued a minor in Biochemistry and Cell Biology. As a student researcher at Rice, he worked in Dr. M. Neal [Waxham's lab](https://sites.google.com/uth.edu/waxham-lab/home) at The University of Texas Health Science Center at Houston, focusing on image analysis of synthetic lipid vesicles under cryo-EM, and co-authored a publication in [*Biophysical Reports*]{.underline}. He also worked in Dr. [Hongjie Li's Lab](https://www.bcm.edu/people-search/hongjie-li-66406) at Baylor College of Medicine under the supervision of Dr. Tzu-Chiao Lu on single-cell data analysis and published a co-authored paper in [*Science*]{.underline}. 

He published multiple papers including [*Blood*]{.underline}, [*Cancer Gene Therapy*]{.underline}, and more with us.

### Brunno Macedo - PhD student

He received a Bachelor's degree in Biomedical Sciences from the [Federal University of Pernambuco in Brazil](https://en.wikipedia.org/wiki/Federal_University_of_Pernambuco), where he gained experience in clinical and laboratory hematology while working as a teacher's assistant for both undergraduate and professional specialization courses for two years. He recently completed a Master of Sciences degree from the [University of São Paulo](https://en.wikipedia.org/wiki/University_of_S%C3%A3o_Paulo) at Ribeirão Preto Medical School (Internal Medicine Graduate Program). During his Master's program, he conducted research in [Dr. Fabiola Traina's lab](https://rio.fmrp.usp.br/fabiolatraina/), which focuses on molecular alterations and signaling pathways in myeloid neoplasms. Currently, Brunno is a PhD student at the University of Alabama at Birmingham.

