---
title: "Publicity/Press"
# listing:
#   contents: people
#   sort: "date desc"
#   type: default
#   categories: false
#   sort-ui: false
#   filter-ui: false
page-layout: full
title-block-banner: true
---

Dr. Changde Cheng's achievements and scientific discoveries have been recognized and reported in professional journals and news media across America, Europe, and Asia, in multiple languages.

>1. 2023 April: Cheng speaks at the Evolvability conference organized by the Center of Advanced Study (CAS) at the Norwegian Academy of Science and Letters.
20. 2022: Our single-cell RNA-seq analysis method was rated highly by researchers at the University of Sydney in [Genome Biology](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-022-02622-0) .
19. 2022: Our work in aging and genetics is featured in a popular undergraduate textbook -  Evolution.
18. 2021: Encouragement from Stanford professor of biology Dmitri Petrov - “A fascinating paper that passes my ’so jealous - why didn’t I think of this?’ test by a big margin." 
17. 2021: Professor Thomas Flatt from the University of Fribourg in Switzerland, recommended our research on aging and molecular evolution (Faculty of 1000).
16. 2020: Our work on sex-specific selection and transcriptome was in the top 10\% most cited in PLoS Genetics.
15. 2018:	Dr. Cheng's work was highlighted by Carin Moonin in Notre Dame News -  [What makes a good malaria vector](https://science.nd.edu/news/what-makes-a-good-malaria-vector/). 
14. 2016: Professor Deborah Charlesworth from the University of Edinburgh recommended our work on sex-specific selection and gene expression (Faculty of 1000).
13. 2016: Our Y chromosome study was highly recommended by Seth Redmond and  Daniel Neafsey from the Broad Institute of MIT and Harvard - [Trends in Parasitology](https://www.cell.com/trends/parasitology/comments/S1471-4922(16)30065-4).
12. 2016: Our Y chromosome study was highlighted in [Phys.org](https://phys.org/news/2016-03-technology-sequence-mosquito-sex-chromosome.html#:~:text=A%20team%20of%20researchers%20with,family%20of%20malaria%20spreading%20mosquitoes.): "new technology to sequence mosquito sex chromosome.''
11. 2016: Our Y chromosome paper was highlighted in Sheng Wu Tong and Yi Du - "mosquito Y chromosome sequenced."
10. 2016: ``Scientists unlock genetic secret that could help fight malaria.'' in 	[EurekAlert!](https://www.eurekalert.org/news-releases/590789)
9. 2016: "Researchers lay groundwork for advanced disease control", as highlighted by Sarah Craig, - [ScienceDaily](https://www.sciencedaily.com/releases/2016/04/160404141904.htm).
8. 2012: Professor Nico M van Straalen from Vrije Universiteit Amsterdam recommended our ecological genomics study of chromosomal inversions - [Faculty of 1000](https://facultyopinions.com/prime/13489095).
7. 2012: Our work on chromosomal inversions was featured on the cover of the April issue of Genetics -[Eck Institute](https://globalhealth.nd.edu/news-events/news/ecological-genomics-of-anopheles-gambiae-along-a-latitudinal-cline-a-population-resequencing-approach/).
6. 2012: Professor Patrik Nosil from the University of Colorado, Boulder, recognized our 'incidental island' hypothesis in the book [Oxford Series in Ecology and Evolution: Ecological Speciation](https://www.google.com/books/edition/Ecological_Speciation/RCDyXbaMEVAC?hl=en&gbpv=0).
5. 2011: Mark Kirkpatrick (University of Texas at Austin) and  Andrew Kern (Rutgers University) highlighed my ecological genomics research - [Genetics](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3316636/).
4. 2011: Paul Roepe (Georgetown University), George Dimopoulos (Imperial College London), Thomas Mitchell-Olds (Duke University), and Bao-Hua Song (the University of North Carolina at Charlotte) recommended our study on the divergence of resistance to Plasmodium - [Faculty of 1000](https://facultyopinions.com/search/articles?query=10.3410/f.7614956.10737056).
3. 2010: W. Gilroy highlighted our work on immunity in emerging species of a major mosquito carrier of malaria - [ScienceDaily](https://www.sciencedaily.com/releases/2010/12/101220150940.htm)
2. 2010: Thomas Turner (UC Santa Barbara) and  Matthew Hahn (Indiana University, Bloomington) recommended our paper on "speciation or divergent islands" - [Molecular Ecology](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-294X.2010.04532.x).
21. 2010: Cheng is awarded the Genomics and Bioinformatics Fellowship at the Eck Institute for Global Health - [Notre Dame News](https://science.nd.edu/news/six-students-receive-genomics-and-bioinformatics-fellowships/).
