---
title: "What is rotation matrix"
author: "Changde Cheng"
date: "2017-06-09"
#bibliography: references.bib
---

I find rotation matrices fascinating. A rotation matrix can represent a rotation in Euclidean space. A rotation matrix is an orthogonal matrix with determinant 1. 

A rotation in two dimension through an angle $\theta$ can be represented as:
$$R(\theta)=
\begin{pmatrix}
\cos \theta & -\sin \theta \\
\sin \theta & \phantom{-}\cos \theta
\end{pmatrix}$$

A reverse rotation is:
$$R(-\theta)=
\begin{pmatrix}
\phantom{-}\cos \theta & \sin \theta \\
-\sin \theta & \cos \theta
\end{pmatrix}$$

Note that $R(-\theta) = R(\theta)^{\mathrm T} = R(\theta)^{-1}$, which tells that $R(\theta$ is orthogonal. Another thing to note is that two dimension rotation have one-dimension representation through $\theta$. 

We find the set of rotation matrices as:
$$SO(n) = \{\mathbf R \in \mathbb{R}^{n\times n}: \mathbf{R R^T = I}, ~\det{\mathbf R} = 1 \}.$$

With matrix product operation, the set in becomes a group: Special Orthogonal Group. Recall that a group is a set with a binary operation, satisfying several rules (associativity, identity element, inverser element). The rotation group $SO(n)$ is a continuous group (Lie group). 

Now take a look at $SO(2)$. Consider two rotations $R(\alpha)$ and $R(\beta)$. We calculate the product of two rotations, and we guess it is $R(\alpha + \beta)$. But let us do a calculation:
$$R(\alpha) R(\beta) = 
\begin{pmatrix}
\cos{\alpha} & -\sin{\alpha} \\
\sin{\alpha} & \cos{\alpha} 
\end{pmatrix}
\begin{pmatrix}
\cos{\beta} & -\sin{\beta} \\
\sin{\beta} & \cos{\beta} 
\end{pmatrix}=
\begin{pmatrix}
\cos{(\alpha+\beta)} & -\sin{(\alpha+\beta)} \\
\sin{(\alpha+\beta)} & \cos{(\alpha+\beta)} 
\end{pmatrix}$$
This result gives us something extra: commutativity $R(\alpha) R(\beta) = R(\alpha+\beta) =R(\beta) R(\alpha)$. In other words, $SO(2)$ is abelian.

But $SO(3)$ is not abelian. Consider two elements in $SO(3)$:

$$R_a =
\begin{pmatrix}
0 & -1 & 0\\
1 & 0 &0 \\
0 & 0 & 1
\end{pmatrix},$$

and 

$$R_b =
\begin{pmatrix}
1 & 0 & 0 \\
0 & 0 & -1 \\
0 & 1 & 0 
\end{pmatrix}.$$

The two matrices are constructed by embedding the elements in $SO(2)$ in a $3\times 3$ matrix.

Now we calculate $R_a R_b$:

$$R_a R_b = \begin{pmatrix}
0 & 0 & 1 \\
1 & 0 & 0 \\
0 & 1 & 0 
\end{pmatrix},$$

and $R_b R_a$:

$$R_b R_a = \begin{pmatrix}
0 & -1 & 0 \\
0 & 0 & -1 \\
1 & 0 & 0 
\end{pmatrix}.$$

We found that $R_a R_b \ne R_b R_a$, and $SO(3)$ is not abelian.
