---
title: "What is canonical correlation"
author: "Changde Cheng"
date: "2022-10-18"
---

Canonical correlation provides a characterization of relations between two systems. Canonical correlation analysis works by identifying corresponding pairs of components that are highly correlated across systems. 

Here is an example. Suppose we have RNA-seq results for a sample of patients, and we also measured their methylation profiles, say by EPIC-850k array. We want to know the relation between gene expression and methylation, which is very complicated given 50,000 genes and 800,000 probes. Canonical correlation analysis can be helpful to give us executive summary on the relation by reducing hundreds of thousands of genes and probes to a handful component pairs.

### What is Canonical Correlation?

Given two random vectors $\mathbf x$ and $\mathbf y$:

$$\mathbf{x} = 
\begin{pmatrix}
x_1 \\
x_2 \\
\cdots \\
x_p
\end{pmatrix}, \qquad
\mathbf{y} = 
\begin{pmatrix}
y_1 \\
y_2 \\
\cdots \\
y_q
\end{pmatrix}$$

Canonical variables are a pair of corresponding vectors $\mathbf{a} \in R_p$ and $\mathbf{b} \in R_q$ which maximize the correlation:
$$\mathrm{cor}(\mathbf{a_1^T x},\mathbf{b_1^T y}) = \max_{\substack{\mathrm{var}(\mathbf{a^T x})=1 \\ \mathrm{var}(\mathbf{b^T y})=1}}{\mathrm{cor}(\mathbf{a^T x},\mathbf{b^T y})},
$${#eq-eq1}
where $\mathbf{a_1^T x}$ and $\mathbf{b_1^T y}$ are called the first pair of canonical variables. There can be more canonical variables out there that are not correlated with each other. 

#### Canonical variables from eigenvectors

Consider the covariance matrix $V$ of the stacked random vector $\pmatrix{\mathbf{x}\\ \mathbf{y}}$:
$$V = 
\begin{pmatrix}
\mathrm{var}(\mathbf{x}) & \mathrm{cov}(\mathbf{x},\mathbf{y})\\
\mathrm{cov}(\mathbf{y},\mathbf{x}) & \mathrm{var}(\mathbf{y})
\end{pmatrix}=
\begin{pmatrix}
V_{xx} & V_{xy}\\
V_{yx} & V_{yy}
\end{pmatrix}$${#eq-eq2}

The correlation to maximize in @{eq-eq1} is
$$\mathrm{cor}(\mathbf{a^T x},\mathbf{b^T y})=\frac{ \mathrm{cov}({\mathbf{a^T x},\mathbf{b^T y})} }{ \mathrm{var}(\mathbf{a^T x})^{\frac{1}{2}}~\mathrm{var}(\mathbf{b^T y})^{\frac{1}{2}} } = \mathrm{cov}({\mathbf{a^T x},\mathbf{b^T y})}=\mathbf{a^T} V_{xy} \mathbf{b},$$
as the variances of $\mathbf{a^T x}$ and $\mathbf{b^T y}$ are 1.

By the method of Lagrange multipliers, we set up a function:
$$\begin{align}
G &= \mathrm{cov}(\mathbf{a^T x},\mathbf{b^T y}) - \frac{1}{2} \lambda_1 \left\{ \mathrm{var}(\mathbf{a^T x})-1 \right\} -  \frac{1}{2} \lambda_2 \left\{ \mathrm{var}(\mathbf{b^T y})-1 \right\} \\
&= \mathbf{a^T} V_{xy} \mathbf{b} - \frac{1}{2} \lambda_1 \left\{ \mathbf{a^T} V_{xx} \mathbf{a} -1 \right\} -  \frac{1}{2} \lambda_2 \left\{ \mathbf{b^T} V_{yy} \mathbf{b} -1\right\}
\end{align}
$$

Let 
$$\frac{\partial G}{\partial \mathbf{a}} = 0,\qquad \frac{\partial G}{\partial \mathbf{b}} = 0,$$
from which we reach a systems of linear equations: 
$$\begin{cases}
V_{xy} \mathbf{b} - \lambda_1 V_{xx} \mathbf{a} &= 0,\\
V_{yx} \mathbf{a} - \lambda_2 V_{yy} \mathbf{b} &= 0.
\end{cases}$${#eq-eq3}

From @{eq-eq3}, we get:

$$\begin{cases}
\lambda_1  = \lambda_1 \mathbf{a^T} V_{xx} \mathbf{a} = \mathbf{a^T} V_{xy} \mathbf{b},\\
\lambda_2  = \lambda_2 \mathbf{b^T} V_{yy} \mathbf{b} = \mathbf{b^T} V_{yx} \mathbf{a} = \lambda_1^{\mathrm T} = \lambda_1.
\end{cases}$${#eq-eq4}

Therefore, @{eq-eq3} becomes:
$$\begin{cases}
V_{xy} \mathbf{b} - \lambda V_{xx} \mathbf{a} &= 0,\\
V_{yx} \mathbf{a} - \lambda V_{yy} \mathbf{b} &= 0.
\end{cases}$${#eq-eq5}

Solve $\mathbf{a}$ from the first equation in @{eq-eq5} and substitute into the second equation in @{eq-eq5}. When $\lambda \ne 0$, we have:
$$V_{yy}^{-1} V_{yx} V_{xx}^{-1} V_{xy} \mathbf{b} =  \lambda^2 \mathbf{b} $$
Therefor, $\mathbf{b}$ is an eigenvector of $V_{yy}^{-1} V_{yx} V_{xx}^{-1} V_{xy}$ and $\lambda^2$ its corresponding eigenvalue. Similarly, $\mathbf{a}$ is an eigenvector of $V_{xx}^{-1} V_{xy} V_{yy}^{-1} V_{yx}$ and $\lambda^2$ its corresponding eigenvalue. Note that $\lambda = \mathrm{cor}(\mathbf{a^T x},\mathbf{b^T y})$, is a canonical correlation.

### Connection to Principal Angles

The canonical correlation is equal to the cosine of principal angles, $\theta_1, \theta_2, \cdots$, between two subspaces $M(\mathbf{x})$ and $M(\mathbf{y})$, spanned by linear functions of $\mathbf{x}$ and $\mathbf{y}$. The connection to cosine of principal angles is hinted by @{eq-eq1}:
$$\mathrm{cor}(\mathbf{a^T x},\mathbf{b^T y})=\frac{ \mathrm{cov}({\mathbf{a^T x},\mathbf{b^T y})} }{ \mathrm{var}(\mathbf{a^T x})^{\frac{1}{2}}~\mathrm{var}(\mathbf{b^T y})^{\frac{1}{2}} } = \frac{ \langle \mathbf{a^T x},\mathbf{b^T y} \rangle }{ \Vert \mathbf{a^T x}\Vert~\Vert \mathbf{b^T y}\Vert },$$

Recall that the cosines of principal angles between subspace $M(\mathbf x)$ and $M(\mathbf y)$, with orthonormal bases $\mathbf{x}$ and $\mathbf{y}$ are singular values of the projection map $\mathsf{Proj}: M(\mathbf x) \to M(\mathbf y)$. In other words, represent $\mathsf{Proj}$ by matrix $P$, then we find the principal angles by singular value decomposition:
$$P=(\langle \mathbf{x}_i, \mathbf{y}_j \rangle)_{i,j} = U \Sigma V = U
\begin{pmatrix}\cos{\theta_1} &  0 &\cdots & 0 \\
0 & \cos{\theta_2} &  \cdots & 0 \\
\cdots &  \cdots & \cdots &\cdots  \\
0 &  0 &\cdots &  \cos{\theta_k}
\end{pmatrix}
V$$



